In [1]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [2]:
# Read data from the CSV into a dataframe

loc = "C:/Users/hsanb/Desktop/Datasets/"

raw_data_1 = pd.read_csv(loc + 'E0.csv')
raw_data_2 = pd.read_csv(loc + 'E01.csv')
raw_data_3 = pd.read_csv(loc + 'E02.csv')
raw_data_4 = pd.read_csv(loc + 'E03.csv')
raw_data_5 = pd.read_csv(loc + 'E04.csv')
raw_data_6 = pd.read_csv(loc + 'E05.csv')
raw_data_7 = pd.read_csv(loc + 'E06.csv')
raw_data_8 = pd.read_csv(loc + 'E07.csv')
raw_data_9 = pd.read_csv(loc + 'E08.csv')
raw_data_10 = pd.read_csv(loc + 'E09.csv')
raw_data_11 = pd.read_csv(loc + 'E010.csv')
raw_data_12 = pd.read_csv(loc + 'E011.csv')
raw_data_13 = pd.read_csv(loc + 'E012.csv')
raw_data_14 = pd.read_csv(loc + 'E013.csv')
raw_data_15 = pd.read_csv(loc + 'E014.csv')

In [3]:
raw_data_6.drop(380,inplace=True)

In [4]:
#Gets all the common statistics related to gameplay
raw_data_1.drop(['Date','Referee','Div','HTR', 'AvgAHH', 'MaxCAHH', 'PC<2.5', 'AHh', 'WHCA', 'B365AHA', 'IWCD', 'MaxA', 'BWCD', 'MaxC>2.5', 'Max<2.5',
                 'AvgCD', 'Time', 'MaxAHH', 'MaxD', 'MaxH', 'AvgCA', 'Avg>2.5', 'BWCH', 'B365C>2.5', 'PAHA', 'VCCH', 
                 'Avg<2.5', 'IWCH', 'AvgAHA', 'AvgC<2.5', 'B365C<2.5', 'AvgCH', 'VCCA', 'WHCH', 'VCCD', 'IWCA', 'MaxCA', 
                 'MaxCAHA', 'AvgC>2.5', 'AvgH', 'MaxCH', 'BWCA', 'PC>2.5', 'AvgA', 'B365<2.5', 'B365CA', 'P<2.5', 'AHCh', 
                 'B365CD', 'B365CAHH', 'AvgCAHA', 'P>2.5', 'AvgD', 'PCAHH','PSCH', 'PSCA', 'PSD', 'PSCD', 'PSH', 'PSA',
                 'PCAHA', 'B365AHH', 'MaxCD', 'B365CH', 'B365CAHA', 'B365>2.5', 'MaxC<2.5', 'Max>2.5', 'MaxAHA', 'AvgCAHH',
                 'PAHH', 'WHCD'],axis=1, inplace=True)
columns_req  =  raw_data_1.columns               

playing_statistics_1 = raw_data_1[columns_req]                      
playing_statistics_2 = raw_data_2[columns_req]
playing_statistics_3 = raw_data_3[columns_req]
playing_statistics_4 = raw_data_4[columns_req]
playing_statistics_5 = raw_data_5[columns_req]
playing_statistics_6 = raw_data_6[columns_req]
playing_statistics_7 = raw_data_7[columns_req]
playing_statistics_8 = raw_data_8[columns_req]
playing_statistics_9 = raw_data_9[columns_req]
playing_statistics_10 = raw_data_10[columns_req]
playing_statistics_11 = raw_data_11[columns_req]   
playing_statistics_12 = raw_data_12[columns_req]
playing_statistics_13 = raw_data_13[columns_req]
playing_statistics_14 = raw_data_14[columns_req]
playing_statistics_15 = raw_data_15[columns_req]

In [5]:
playing_statistics_1.columns

Index(['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HS',
       'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR',
       'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA'],
      dtype='object')

In [6]:
a=playing_statistics_1.groupby('HomeTeam').mean().T
a.columns

Index(['Arsenal', 'Aston Villa', 'Bournemouth', 'Brighton', 'Burnley',
       'Chelsea', 'Crystal Palace', 'Everton', 'Leicester', 'Liverpool',
       'Man City', 'Man United', 'Newcastle', 'Norwich', 'Sheffield United',
       'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves'],
      dtype='object', name='HomeTeam')

Get MatchWeek:

In [7]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(len(playing_stat)):
        MatchWeek.append(j)
        if ((i + 1)% 10) == 0: # 10 because we have 20 teams
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

playing_statistics_1 = get_mw(playing_statistics_1)
playing_statistics_2 = get_mw(playing_statistics_2)
playing_statistics_3 = get_mw(playing_statistics_3)
playing_statistics_4 = get_mw(playing_statistics_4)
playing_statistics_5 = get_mw(playing_statistics_5)
playing_statistics_6 = get_mw(playing_statistics_6)
playing_statistics_7 = get_mw(playing_statistics_7)
playing_statistics_8 = get_mw(playing_statistics_8)
playing_statistics_9 = get_mw(playing_statistics_9)
playing_statistics_10 = get_mw(playing_statistics_10)
playing_statistics_11 = get_mw(playing_statistics_11)
playing_statistics_12 = get_mw(playing_statistics_12)
playing_statistics_13 = get_mw(playing_statistics_13)
playing_statistics_14 = get_mw(playing_statistics_14)
playing_statistics_15 = get_mw(playing_statistics_15)

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [8]:
playing_statistics_1['HomeTeam'][-10:]

219        Watford
220        Arsenal
221       Brighton
222       Man City
223        Norwich
224    Southampton
225       West Ham
226      Newcastle
227        Burnley
228      Liverpool
Name: HomeTeam, dtype: object

In [9]:
playing_statistics_1.iloc[209]

HomeTeam    Sheffield United
AwayTeam            West Ham
FTHG                       1
FTAG                       0
FTR                        H
HTHG                       0
HTAG                       0
HS                        13
AS                         7
HST                        3
AST                        2
HF                        11
AF                         6
HC                         7
AC                         3
HY                         1
AY                         0
HR                         0
AR                         0
B365H                   1.95
B365D                    3.4
B365A                      4
BWH                        2
BWD                      3.4
BWA                        4
IWH                        2
IWD                      3.4
IWA                     3.85
WHH                        2
WHD                      3.4
WHA                      3.9
VCH                     2.05
VCD                      3.4
VCA                      3.9
MW                        21
Name: 209, dtype: object

In [10]:
#Padding   
def Padding(val,Team,teams,L):
    for i in Team:
        teams[i].extend([val]*(L-1-len(teams[i])))
    return teams

# Get previous team stats

In [11]:
a=2
if(a):
    print('true')

true

In [12]:
def get_previous_stat(team_stat,varH,varA,mw):
    teams = {}
    Team=team_stat.groupby('HomeTeam').mean().T.columns
    L=(len(Team)-1)*2+1
    j=0
    for i in Team:
        teams[i] = [[0]*len(varH)] 
    
    for i in range(len(team_stat)):
        j=1*(i>(len(team_stat)-10))
        diff=mw-len(teams[team_stat.iloc[i].HomeTeam])
       
        varh = list(team_stat.iloc[i][varH])
        vara = list(team_stat.iloc[i][varA])
        
        if ((diff)&(j)):

            for d in range(diff+1):
                teams[team_stat.iloc[i].HomeTeam].append(teams[team_stat.iloc[i].HomeTeam][-1])
        else:
            teams[team_stat.iloc[i].HomeTeam].append(varh)
            
        diff=mw-len(teams[team_stat.iloc[i].AwayTeam])

        if ((diff)&(j)):  
            for d in range(diff+1):
                teams[team_stat.iloc[i].AwayTeam].append(teams[team_stat.iloc[i].AwayTeam][-1])
        else:
            teams[team_stat.iloc[i].AwayTeam].append(vara)
    
    
    #Padding        
    teams=Padding([0]*len(varH),Team,teams,L+1)
    previous_stat=pd.DataFrame(teams, index=[i for i in range(0,L)]).T
    return previous_stat

In [13]:
def previous_stat(playing_statistics):
    varH=['FTHG','HTHG','HST','HS', 'HF', 'HC','HY', 'HR', 'B365H', 'B365D','BWH', 'BWD','IWH', 'IWD','WHH', 'WHD','VCH', 'VCD'] 
    varA=['FTAG','HTAG','AST','AS', 'AF', 'AC','AY', 'AR', 'B365A', 'B365D','BWA', 'BWD','IWA', 'IWD','WHA', 'WHD','VCA', 'VCD']
    mw=max(playing_statistics['MW'])
    previous_stat=get_previous_stat(playing_statistics,varH,varA,mw)
    for i in range(len(playing_statistics)):
        j=playing_statistics.iloc[i]['MW']-1 
        ht=playing_statistics.iloc[i]['HomeTeam']
        at=playing_statistics.iloc[i]['AwayTeam']

        playing_statistics.at[i,varH]=previous_stat[j][ht]
        playing_statistics.at[i,varA]=previous_stat[j][at]

    return playing_statistics

In [14]:
#print(playing_statistics_1[:21])
# Apply to each dataset
playing_statistics_1= previous_stat(playing_statistics_1)

In [15]:
# print(playing_statistics_1[:21])
playing_statistics_6= previous_stat(playing_statistics_6)

C:\Users\hsanb\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [16]:
playing_statistics_2= previous_stat(playing_statistics_2)
playing_statistics_3= previous_stat(playing_statistics_3)
playing_statistics_4= previous_stat(playing_statistics_4)
playing_statistics_5= previous_stat(playing_statistics_5)

playing_statistics_7= previous_stat(playing_statistics_7)
playing_statistics_8= previous_stat(playing_statistics_8)
playing_statistics_9= previous_stat(playing_statistics_9)
playing_statistics_10= previous_stat(playing_statistics_10)
playing_statistics_11= previous_stat(playing_statistics_11)
playing_statistics_12= previous_stat(playing_statistics_12)
playing_statistics_13= previous_stat(playing_statistics_13)
playing_statistics_14= previous_stat(playing_statistics_14)
playing_statistics_15= previous_stat(playing_statistics_15)

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK  **

#Calculate goals scored and goals conceded for each team

In [17]:

# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    Team=playing_stat.groupby('HomeTeam').mean().T.columns
    L=(len(Team)-1)*2+1

    for i in Team:
        teams[i] = [] 
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
            HTGS = playing_stat.iloc[i]['FTHG']
            ATGS = playing_stat.iloc[i]['FTAG']
            teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
            teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    #L=len(teams[list(teams.keys())[0]])+1
    
    #Padding        
    teams=Padding(0,Team,teams,L)
    

    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,L)]).T # premier league teams number 
    GoalsScored[0] = 0
    
    # Aggregate to get uptil that point
    for i in range(2,L):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
        
    return GoalsScored
        
# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    Team=playing_stat.groupby('HomeTeam').mean().T.columns
    L=(len(Team)-1)*2+1
    for i in Team:
        teams[i] = []
    
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
            ATGC = playing_stat.iloc[i]['FTHG']
            HTGC = playing_stat.iloc[i]['FTAG']
            teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
            teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
            
    #Padding        
    teams=Padding(0,Team,teams,L)
            
    #L=len(teams[list(teams.keys())[0]])+1
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,L)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,L):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GS = get_goals_scored(playing_stat)
    GC = get_goals_conceded(playing_stat)
    print('GS=\n',GS)
       
    
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(len(playing_stat)):
        j=playing_stat.loc[i]['MW'] # if don't make previous stat, add -1 #before playing match week
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat
    


# Apply to each dataset
playing_statistics_1= get_gss(playing_statistics_1)
print(playing_statistics_1)
playing_statistics_2= get_gss(playing_statistics_2)
playing_statistics_3= get_gss(playing_statistics_3)
playing_statistics_4= get_gss(playing_statistics_4)
playing_statistics_5= get_gss(playing_statistics_5)
playing_statistics_6= get_gss(playing_statistics_6)
playing_statistics_7= get_gss(playing_statistics_7)
playing_statistics_8= get_gss(playing_statistics_8)
playing_statistics_9= get_gss(playing_statistics_9)
playing_statistics_10= get_gss(playing_statistics_10)
playing_statistics_11= get_gss(playing_statistics_11)
playing_statistics_12= get_gss(playing_statistics_12)
playing_statistics_13= get_gss(playing_statistics_13)
playing_statistics_14= get_gss(playing_statistics_14)
playing_statistics_15= get_gss(playing_statistics_15)

GS=
                   1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal            0   1   3   4   6   8  11  12  13  13  ...  29  29  29  29
Aston Villa        0   1   2   4   4   4   6   8  13  15  ...  28  28  28  28
Bournemouth        0   1   3   4   5   8  11  13  13  13  ...  19  19  19  19
Brighton           0   3   4   4   4   5   5   5   8   9  ...  24  24  24  24
Burnley            0   3   4   5   5   6   8  10  11  12  ...  24  24  24  24
Chelsea            0   0   1   4   6  11  12  14  18  19  ...  37  37  37  37
Crystal Palace     0   0   0   2   3   3   4   6   8   8  ...  20  20  20  20
Everton            0   0   1   1   4   5   5   6   6   8  ...  25  25  25  25
Leicester          0   0   1   3   6   6   8  13  14  16  ...  47  47  47  47
Liverpool          0   4   6   9  12  15  17  18  20  21  ...  49  49  49  49
Man City           0   5   7  10  14  16  24  27  27  29  ...  62  62  62  62
Man United         0   4   5   6   7   8   8   9   9  10  ...  36  36  36  36
Newcastle          0   0   1   2   3   4   4   4   5   5  ...  21  21  21  21
Norwich            0   1   4   6   6   9   9   9  10  10  ...  22  22  22  22
Sheffield United   0   1   2   3   5   5   7   7   7   8  ...  24  24  24  24
Southampton        0   0   1   3   4   5   6   7   8   9  ...  27  27  27  27
Tottenham          0   3   5   5   7  11  12  14  14  15  ...  38  38  38  38
Watford            0   0   0   1   2   4   4   4   4   5  ...  19  19  19  19
West Ham           0   0   1   4   6   6   8  10  11  11  ...  28  28  28  28
Wolves             0   0   1   2   4   6   7   9  11  12  ...  31  31  31  31

                  34  35  36  37  38  0
Arsenal           29  29  29  29  29   0
Aston Villa       28  28  28  28  28   0
Bournemouth       19  19  19  19  19   0
Brighton          24  24  24  24  24   0
Burnley           24  24  24  24  24   0
Chelsea           37  37  37  37  37   0
Crystal Palace    20  20  20  20  20   0
Everton           25  25  25  25  25   0
Leicester         47  47  47  47  47   0
Liverpool         49  49  49  49  49   0
Man City          62  62  62  62  62   0
Man United        36  36  36  36  36   0
Newcastle         21  21  21  21  21   0
Norwich           22  22  22  22  22   0
Sheffield United  24  24  24  24  24   0
Southampton       27  27  27  27  27   0
Tottenham         38  38  38  38  38   0
Watford           19  19  19  19  19   0
West Ham          28  28  28  28  28   0
Wolves            31  31  31  31  31   0

[20 rows x 39 columns]
           HomeTeam          AwayTeam  FTHG  FTAG  FTR  HTHG  HTAG    HS  \
0         Liverpool           Norwich     0     0    H   0.0   0.0   0.0
1          West Ham          Man City     0     0    A   0.0   0.0   0.0
2       Bournemouth  Sheffield United     0     0    D   0.0   0.0   0.0
3           Burnley       Southampton     0     0    H   0.0   0.0   0.0
4    Crystal Palace           Everton     0     0    D   0.0   0.0   0.0
..              ...               ...   ...   ...  ...   ...   ...   ...
224     Southampton            Wolves     2     1  NaN   1.0   1.0  16.0
225        West Ham           Everton     0     1  NaN   0.0   1.0   7.0
226       Newcastle           Chelsea     1     3  NaN   1.0   2.0   5.0
227         Burnley         Leicester     0     1  NaN   0.0   1.0   7.0
228       Liverpool        Man United     1     4  NaN   1.0   1.0  13.0

       AS   HST  ...  WHD   WHA   VCH  VCD   VCA  MW  HTGS  ATGS  HTGC  ATGC
0     0.0   0.0  ...  0.0  0.00   0.0  0.0  0.00   1     0     0     0     0
1     0.0   0.0  ...  0.0  0.00   0.0  0.0  0.00   1     0     0     0     0
2     0.0   0.0  ...  0.0  0.00   0.0  0.0  0.00   1     0     0     0     0
3     0.0   0.0  ...  0.0  0.00   0.0  0.0  0.00   1     0     0     0     0
4     0.0   0.0  ...  0.0  0.00   0.0  0.0  0.00   1     0     0     0     0
..    ...   ...  ...  ...   ...   ...  ...   ...  ..   ...   ...   ...   ...
224   9.0  10.0  ...  4.2  1.44   5.4  4.2  1.45  23    27    31    37    36
225  14.0   2.0  ...  3.5  1.75   3.9  3.6  1.91  23    28    25    19    30
226  18.0   1.0  ...  5.5  1.29   9.0  5.5  1.29  23    21    37    32    28
227   5.0   2.0  ...  3.9  1.63  12.0  4.0  1.65  23    24    47    31    27
228  13.0   7.0  ...  5.0  1.35   1.7  5.0  1.36  23    49    36    28    29

[229 rows x 39 columns]
GS=
                 1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal          0   0   2   5   8  10  12  14  19  22  ...  61  63  63  64
Bournemouth      0   2   4   6   6  10  10  12  16  16  ...  39  39  41  41
Brighton         0   0   3   3   5   7   8   8   9  10  ...  31  31  31  31
Burnley          0   0   1   3   3   3   7   9  10  10  ...  32  34  36  38
Cardiff          0   0   0   0   2   3   3   4   4   8  ...  26  27  28  28
Chelsea          0   3   6   8  10  14  14  15  18  20  ...  50  52  54  57
Crystal Palace   0   2   2   3   3   4   4   5   5   5  ...  35  36  38  38
Everton          0   2   4   6   7   8   8  11  13  15  ...  40  42  44  46
Fulham           0   0   1   5   7   7   8   8   9  11  ...  27  28  29  30
Huddersfield     0   0   1   1   2   2   3   3   4   4  ...  15  15  15  15
Leicester        0   1   3   5   6   8  11  13  14  15  ...  35  38  41  43
Liverpool        0   4   6   7   9  11  14  15  15  16  ...  64  68  70  72
Man City         0   2   8   9  11  14  19  21  21  26  ...  82  85  87  90
Man United       0   2   4   4   6   8   9  10  13  15  ...  58  58  60  61
Newcastle        0   1   1   2   3   4   4   4   6   6  ...  27  27  29  29
Southampton      0   0   1   2   4   6   6   6   6   6  ...  32  34  35  38
Tottenham        0   2   5   8   9  10  12  14  15  16  ...  56  57  58  62
Watford          0   2   5   7   9  10  11  11  11  13  ...  41  42  43  43
West Ham         0   0   1   2   2   5   5   8   8   8  ...  35  35  39  39
Wolves           0   2   2   3   4   5   6   8   9   9  ...  35  36  36  37

                34  35  36  37  38  0
Arsenal         66  68  69  69  70   0
Bournemouth     41  42  42  45  46   0
Brighton        31  31  31  32  33   0
Burnley         40  42  44  44  44   0
Cardiff         28  30  30  30  32   0
Chelsea         59  59  61  62  65   0
Crystal Palace  39  40  43  43  46   0
Everton         48  48  52  52  54   0
Fulham          30  31  32  33  33   0
Huddersfield    16  17  18  18  19   0
Leicester       45  45  47  50  50   0
Liverpool       75  77  79  84  87   0
Man City        93  94  96  97  98   0
Man United      61  61  61  62  63   0
Newcastle       29  29  32  33  35   0
Southampton     41  42  43  46  46   0
Tottenham       66  66  67  67  67   0
Watford         43  45  46  47  47   0
West Ham        39  40  42  43  46   0
Wolves          37  37  40  42  43   0

[20 rows x 39 columns]

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

GS=
                 1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal          0   4   4   4   7   7   9  11  12  17  ...  52  55  58  59
Bournemouth      0   0   0   1   1   3   4   4   4   6  ...  35  36  37  39
Brighton         0   0   0   0   3   4   5   5   6   9  ...  28  28  28  29
Burnley          0   3   3   4   5   6   6   7   8   8  ...  24  26  28  30
Chelsea          0   2   4   6   8   8  12  12  13  17  ...  50  51  52  53
Crystal Palace   0   0   0   0   0   0   0   0   2   2  ...  27  28  29  31
Everton          0   1   2   2   2   2   4   4   5   7  ...  33  35  37  39
Huddersfield     0   3   4   4   4   5   5   5   5   7  ...  25  25  25  25
Leicester        0   3   5   5   6   7   9   9  10  12  ...  41  45  47  48
Liverpool        0   3   4   8   8   9  12  13  13  14  ...  67  68  69  74
Man City         0   2   3   5  10  16  21  22  29  32  ...  83  85  88  91
Man United       0   4   8  10  12  16  17  21  21  22  ...  56  58  60  60
Newcastle        0   0   0   3   4   6   6   7   9  10  ...  27  30  31  33
Southampton      0   0   3   3   3   4   4   5   7   8  ...  29  29  31  33
Stoke            0   0   1   2   4   5   5   7   9  10  ...  28  28  29  30
Swansea          0   0   0   2   2   2   3   3   5   6  ...  25  25  26  27
Tottenham        0   2   3   4   7   7  10  14  15  19  ...  52  55  58  59
Watford          0   3   5   5   7   7   9  11  13  15  ...  39  39  39  41
West Brom        0   1   2   3   4   4   4   6   7   7  ...  22  23  24  25
West Ham         0   0   2   2   4   4   6   7   8   8  ...  35  38  39  40

                34   35   36   37   38  0
Arsenal         63   64   69   74   75   0
Bournemouth     41   43   43   43   44   0
Brighton        31   32   32   33   34   0
Burnley         32   33   34   34   34   0
Chelsea         56   57   58   59   60   0
Crystal Palace  32   34   37   37   39   0
Everton         40   41   42   43   44   0
Huddersfield    25   26   26   26   27   0
Leicester       49   49   49   49   52   0
Liverpool       76   76   79   79   79   0
Man City        96  100  100  100  103   0
Man United      60   62   64   64   64   0
Newcastle       33   33   33   34   34   0
Southampton     35   35   37   38   39   0
Stoke           31   32   33   34   35   0
Swansea         27   27   27   27   27   0
Tottenham       60   62   62   62   63   0
Watford         43   44   44   44   46   0
West Brom       26   27   28   29   30   0
West Ham        41   42   43   45   45   0

[20 rows x 39 columns]
GS=
                 1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal          0   3   3   6   8  12  15  16  19  19  ...  63  64  64  66
Bournemouth      0   1   1   2   3   3   4   6  12  12  ...  41  41  41  43
Burnley          0   0   2   2   3   3   5   5   6   8  ...  33  33  33  34
Chelsea          0   2   4   7   9  10  10  12  15  19  ...  60  62  62  62
Crystal Palace   0   0   0   1   3   7  10  11  11  12  ...  37  40  43  45
Everton          0   1   3   4   7  10  10  11  12  13  ...  49  53  54  55
Hull             0   2   4   4   5   6   7   7   8   8  ...  26  26  28  32
Leicester        0   1   1   3   4   7   8   8   8  11  ...  32  34  36  36
Liverpool        0   4   4   5   9  11  16  18  18  20  ...  63  66  69  71
Man City         0   2   6   9  11  15  18  18  19  20  ...  58  59  62  62
Man United       0   3   5   6   7   8  12  13  13  13  ...  40  42  44  44
Middlesbrough    0   1   3   3   4   5   6   7   7   7  ...  20  22  23  24
Southampton      0   1   1   2   3   4   7   7  10  11  ...  30  30  32  32
Stoke            0   1   2   2   2   3   4   5   7   9  ...  32  33  33  33
Sunderland       0   1   2   3   3   3   5   6   6   6  ...  24  24  24  24
Swansea          0   1   1   2   4   4   5   6   8   8  ...  38  38  38  39
Tottenham        0   1   2   3   7   8  10  12  13  13  ...  57  60  64  65
Watford          0   1   2   3   7  10  10  12  13  13  ...  35  37  37  38
West Brom        0   1   2   2   2   6   7   8   9  10  ...  36  39  39  39
West Ham         0   1   2   3   5   7   7   8   9  10  ...  39  41  42  42

                34  35  36  37  38  0
Arsenal         68  70  74  78  80   0
Bournemouth     44  44  48  49  51   0
Burnley         34  35  35  37  38   0
Chelsea         66  69  72  73  77   0
Crystal Palace  47  49  49  49  53   0
Everton         59  62  62  62  63   0
Hull            33  34  36  36  36   0
Leicester       36  37  40  41  42   0
Liverpool       73  74  75  75  79   0
Man City        64  66  71  73  76   0
Man United      45  45  46  47  47   0
Middlesbrough   24  25  27  29  30   0
Southampton     32  32  32  34  34   0
Stoke           34  37  37  39  40   0
Sunderland      24  24  24  24  24   0
Swansea         39  41  42  43  45   0
Tottenham       67  69  71  73  79   0
Watford         38  38  38  38  41   0
West Brom       39  39  41  41  42   0
West Ham        43  45  45  46  46   0

[20 rows x 39 columns]
GS=
                 1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal          0   0   2   2   3   5   5  10  13  16  ...  46  48  52  53
Aston Villa      0   1   1   2   4   6   6   8   8   8  ...  21  21  21  21
Bournemouth      0   0   0   4   5   6   8   9  10  11  ...  35  38  41  41
Chelsea          0   2   2   5   6   7   9  11  12  14  ...  43  45  49  49
Crystal Palace   0   3   4   6   8   8   8   9  11  12  ...  32  34  36  37
Everton          0   2   5   5   5   8   8  11  12  12  ...  50  51  51  51
Leicester        0   4   6   7   8  11  13  15  17  19  ...  52  53  54  55
Liverpool        0   1   2   2   2   3   4   7   8   8  ...  39  41  45  49
Man City         0   3   6   8  10  11  12  13  19  24  ...  55  55  59  61
Man United       0   1   2   2   3   6   9  12  12  15  ...  37  38  38  38
Newcastle        0   2   2   2   2   2   3   5   6  12  ...  28  29  31  32
Norwich          0   1   4   5   5   8   9  11  12  14  ...  32  32  32  33
Southampton      0   2   2   2   5   5   7  10  13  15  ...  36  38  41  44
Stoke            0   0   2   3   3   3   5   7   8   9  ...  32  33  34  36
Sunderland       0   2   3   4   6   6   6   6   8   8  ...  35  36  36  36
Swansea          0   2   4   5   7   7   7   8  10  10  ...  29  30  32  33
Tottenham        0   0   2   3   3   4   5   9  11  11  ...  51  53  55  56
Watford          0   2   2   2   2   3   5   5   6   6  ...  29  30  30  31
West Brom        0   0   0   2   3   3   4   6   6   7  ...  30  30  30  31
West Ham         0   2   3   6   9  11  13  15  17  20  ...  45  47  49  51

                34  35  36  37  38  0
Arsenal         54  56  58  59  61   0
Aston Villa     21  22  24  26  26   0
Bournemouth     43  44  45  46  47   0
Chelsea         53  55  57  59  60   0
Crystal Palace  37  37  38  38  40   0
Everton         52  52  54  55  55   0
Leicester       57  59  63  67  70   0
Liverpool       51  52  54  56  57   0
Man City        64  65  69  71  73   0
Man United      39  40  41  42  44   0
Newcastle       35  36  37  39  39   0
Norwich         36  36  36  36  40   0
Southampton     44  47  51  55  57   0
Stoke           37  37  37  37  38   0
Sunderland      36  36  39  42  45   0
Swansea         35  35  35  38  42   0
Tottenham       59  63  64  66  67   0
Watford         32  35  35  35  37   0
West Brom       31  31  32  33  34   0
West Ham        53  56  57  58  61   0

[20 rows x 39 columns]
GS=
                  1    2    3     4     5     6     7     8     9     10  ...  \
Arsenal         0.0  2.0  4.0   5.0   7.0  10.0  11.0  11.0  13.0  15.0  ...
Aston Villa     0.0  1.0  1.0   3.0   4.0   4.0   4.0   4.0   4.0   4.0  ...
Burnley         0.0  1.0  1.0   1.0   1.0   1.0   1.0   3.0   4.0   5.0  ...
Chelsea         0.0  3.0  5.0  11.0  15.0  16.0  19.0  21.0  23.0  24.0  ...
Crystal Palace  0.0  1.0  2.0   5.0   5.0   8.0  10.0  10.0  11.0  13.0  ...
Everton         0.0  2.0  4.0   7.0   9.0  11.0  12.0  13.0  16.0  19.0  ...
Hull            0.0  1.0  2.0   3.0   5.0   7.0   9.0  11.0  13.0  13.0  ...
Leicester       0.0  2.0  2.0   3.0   4.0   9.0   9.0  11.0  11.0  11.0  ...
Liverpool       0.0  2.0  3.0   6.0   6.0   7.0   8.0  10.0  13.0  13.0  ...
Man City        0.0  2.0  5.0   5.0   7.0   8.0  12.0  14.0  18.0  19.0  ...
Man United      0.0  1.0  2.0   2.0   6.0   9.0  11.0  13.0  15.0  16.0  ...
Newcastle       0.0  0.0  0.0   3.0   3.0   5.0   5.0   7.0   8.0  10.0  ...
QPR             0.0  0.0  0.0   1.0   1.0   3.0   4.0   4.0   6.0   8.0  ...
Southampton     0.0  1.0  1.0   4.0   8.0   9.0  11.0  11.0  19.0  20.0  ...
Stoke           0.0  0.0  1.0   2.0   2.0   4.0   5.0   6.0   8.0   8.0  ...
Sunderland      0.0  2.0  3.0   3.0   5.0   5.0   5.0   8.0   8.0   8.0  ...
Swansea         0.0  2.0  3.0   6.0   8.0   8.0   8.0  10.0  11.0  13.0  ...
Tottenham       0.0  1.0  5.0   5.0   7.0   7.0   8.0   9.0  10.0  11.0  ...
West Brom       0.0  2.0  2.0   2.0   2.0   3.0   7.0   8.0  10.0  12.0  ...
West Ham        0.0  0.0  3.0   4.0   6.0   9.0  10.0  12.0  15.0  17.0  ...

                  30    31    32    33    34    35    36    37    38  0
Arsenal         56.0  59.0  63.0  63.0  66.0  66.0  67.0  68.0  68.0   0
Aston Villa     18.0  18.0  18.0  19.0  22.0  23.0  25.0  26.0  27.0   0
Burnley         26.0  26.0  26.0  26.0  26.0  26.0  26.0  26.0  26.0   0
Chelsea         62.0  63.0  64.0  64.0  64.0  67.0  68.0  69.0  69.0   0
Crystal Palace  34.0  36.0  38.0  42.0  46.0  46.0  46.0  47.0  50.0   0
Everton         36.0  38.0  39.0  40.0  41.0  42.0  44.0  44.0  46.0   0
Hull            28.0  30.0  31.0  31.0  33.0  34.0  35.0  35.0  35.0   0
Leicester       27.0  30.0  32.0  34.0  35.0  36.0  39.0  41.0  41.0   0
Liverpool       43.0  44.0  45.0  45.0  45.0  45.0  47.0  48.0  49.0   0
Man City        59.0  62.0  63.0  65.0  67.0  70.0  71.0  77.0  81.0   0
Man United      50.0  52.0  55.0  59.0  59.0  59.0  59.0  61.0  62.0   0
Newcastle       32.0  33.0  33.0  33.0  34.0  36.0  36.0  37.0  38.0   0
QPR             30.0  31.0  32.0  36.0  36.0  36.0  37.0  37.0  39.0   0
Southampton     40.0  42.0  42.0  44.0  45.0  47.0  48.0  48.0  54.0   0
Stoke           33.0  34.0  35.0  36.0  38.0  39.0  39.0  39.0  39.0   0
Sunderland      23.0  23.0  24.0  25.0  27.0  29.0  29.0  29.0  29.0   0
Swansea         35.0  36.0  39.0  40.0  40.0  43.0  45.0  46.0  48.0   0
Tottenham       47.0  51.0  51.0  51.0  54.0  56.0  56.0  56.0  58.0   0
West Brom       26.0  26.0  27.0  29.0  31.0  31.0  32.0  33.0  36.0   0
West Ham        40.0  41.0  42.0  43.0  43.0  43.0  43.0  43.0  44.0   0

[20 rows x 39 columns]

GS=
                 1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal          0   1   4   5   8  11  13  14  18  20  ...  55  55  55  56
Aston Villa      0   3   6   6   7   8  11  11  11  11  ...  34  35  36  37
Cardiff          0   0   3   3   4   4   6   7   8   8  ...  19  22  25  28
Chelsea          0   2   4   4   4   6   7  10  14  16  ...  53  57  57  63
Crystal Palace   0   0   1   4   4   4   4   5   6   6  ...  17  17  18  21
Everton          0   2   2   2   3   6   9  10  12  14  ...  45  48  51  52
Fulham           0   1   2   2   3   3   4   5   9   9  ...  30  31  31  31
Hull             0   0   1   1   2   5   6   6   7   7  ...  32  34  35  36
Liverpool        0   1   2   3   5   5   8  11  13  17  ...  76  82  84  88
Man City         0   4   6   8   8  12  14  17  20  21  ...  79  81  83  85
Man United       0   0   0   0   2   3   4   6   7  10  ...  43  45  47  51
Newcastle        0   0   0   1   3   5   7   9  11  12  ...  37  38  39  39
Norwich          0   2   2   3   3   3   4   5   6   6  ...  22  23  25  25
Southampton      0   1   2   2   2   3   5   7   8  10  ...  39  43  47  51
Stoke            0   0   2   3   3   4   4   4   4   6  ...  28  29  33  37
Sunderland       0   0   1   2   3   3   4   5   5   7  ...  28  28  30  32
Swansea          0   1   1   3   5   7   8   8  12  12  ...  38  40  42  44
Tottenham        0   1   2   2   4   5   6   6   8   9  ...  36  36  39  39
West Brom        0   0   0   0   1   4   6   7   7   8  ...  32  35  36  39
West Ham         0   2   2   2   2   4   4   7   8   8  ...  31  31  33  35

                34  35  36  37  38  0
Arsenal         56  59  62  65  66   0
Aston Villa     37  38  39  42  42   0
Cardiff         31  31  32  32  32   0
Chelsea         66  69  70  72  72   0
Crystal Palace  22  25  26  26  29   0
Everton         53  55  57  59  61   0
Fulham          32  33  34  36  37   0
Hull            36  36  38  39  40   0
Liverpool       90  93  96  96  99   0
Man City        88  90  92  95  99   0
Man United      51  51  55  55  58   0
Newcastle       39  39  40  40  43   0
Norwich         25  25  25  25  25   0
Southampton     55  56  56  58  59   0
Stoke           38  38  39  39  43   0
Sunderland      34  38  42  43  45   0
Swansea         44  44  46  50  50   0
Tottenham       44  47  50  51  51   0
West Brom       40  41  41  41  41   0
West Ham        36  37  37  37  39   0

[20 rows x 39 columns]
GS=
              1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  34  \
Arsenal       0   0   0   0   6  12  13  16  19  20  ...  58  62  64  67  70
Aston Villa   0   0   1   2   4   5   6   7   7   8  ...  30  33  36  37  38
Chelsea       0   2   4   6   8   8   9  13  17  19  ...  58  60  63  65  67
Everton       0   1   4   4   6   9  12  14  15  16  ...  44  46  48  50  50
Fulham        0   5   7   7  10  12  13  14  15  16  ...  40  40  40  41  42
Liverpool     0   0   2   2   3   4   9   9  10  12  ...  61  62  64  66  66
Man City      0   3   5   8   9  10  12  15  17  18  ...  47  49  50  51  52
Man United    0   0   3   6  10  12  14  17  21  24  ...  69  70  72  74  76
Newcastle     0   2   2   3   5   6   8   8   9  11  ...  38  40  40  41  41
Norwich       0   0   1   2   2   2   2   3   4   5  ...  26  27  28  28  30
QPR           0   0   1   2   2   3   4   6   8   8  ...  24  26  28  30  31
Reading       0   1   2   2   4   6   6   9  10  10  ...  35  36  36  37  37
Southampton   0   2   2   2   3   7   8  10  11  12  ...  40  40  43  45  46
Stoke         0   1   1   3   5   5   7   7   9   9  ...  28  29  29  30  31
Sunderland    0   2   3   4   5   5   6   6   6   7  ...  33  34  34  35  38
Swansea       0   5   8  10  10  10  10  12  14  14  ...  37  37  37  37  37
Tottenham     0   1   2   3   6   8  11  13  15  17  ...  51  51  53  56  58
West Brom     0   3   4   6   6   7   8  11  12  13  ...  41  41  41  42  45
West Ham      0   1   1   4   4   5   7   8  12  13  ...  34  34  35  36  38
Wigan         0   0   2   4   4   5   5   7   8  10  ...  35  36  36  36  38

             35  36  37  38  0
Arsenal      71  72  73  77   0
Aston Villa  38  38  40  41   0
Chelsea      68  69  71  73   0
Everton      50  51  51  53   0
Fulham       42  42  44  45   0
Liverpool    66  72  72  75   0
Man City     52  52  53  55   0
Man United   79  80  80  82   0
Newcastle    41  41  41  43   0
Norwich      32  34  35  39   0
QPR          31  31  31  32   0
Reading      38  39  43  43   0
Southampton  46  46  46  47   0
Stoke        33  34  35  36   0
Sunderland   39  40  41  42   0
Swansea      37  37  40  41   0
Tottenham    59  60  62  64   0
West Brom    47  49  49  49   0
West Ham     40  41  41  41   0
Wigan        41  44  46  47   0

[20 rows x 39 columns]
GS=
              1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  34  \
Arsenal       0   0   0   0   1   2   5   6   8  10  ...  50  53  54  55  58
Aston Villa   0   0   0   0   0   1   2   4   6   7  ...  23  24  25  25  25
Blackburn     0   1   2   2   3   7   8   8   9  10  ...  48  49  49  49  51
Bolton        0   4   6   7   7   7   7   8  11  11  ...  32  32  32  33  35
Chelsea       0   0   2   5   7   8  12  16  19  22  ...  51  52  56  58  59
Everton       0   1   3   6   6   6   6   9   9  10  ...  26  28  30  32  36
Fulham        0   0   0   1   2   4   4  10  10  11  ...  34  34  36  39  40
Liverpool     0   0   2   5   5   5   7   9  10  11  ...  32  33  33  34  34
Man City      0   4   7  12  15  17  19  23  27  33  ...  71  72  75  75  75
Man United    0   2   5  13  18  21  22  24  25  26  ...  73  74  76  78  78
Newcastle     0   0   1   3   5   6   9  11  13  14  ...  41  44  47  49  52
Norwich       0   1   2   3   3   5   7   7  10  11  ...  39  41  42  44  46
QPR           0   0   1   1   1   4   5   5   6   7  ...  32  33  35  35  38
Stoke         0   0   1   2   3   3   4   4   6   7  ...  28  29  29  29  29
Sunderland    0   1   1   1   2   6   7   9  10  12  ...  36  39  42  42  42
Swansea       0   0   0   0   0   3   4   6   7   9  ...  34  34  34  34  34
Tottenham     0   1   3   7   9  11  13  15  18  21  ...  54  54  57  57  57
West Brom     0   1   2   2   3   3   3   5   7   9  ...  37  38  38  41  41
Wigan         0   1   1   3   3   4   5   5   6   6  ...  25  27  29  30  31
Wolves        0   2   4   4   4   4   5   6   6   8  ...  28  29  31  32  32

             35  36  37  38  0
Arsenal      61  62  63  66   0
Aston Villa  25  26  26  27   0
Blackburn    53  55  55  55   0
Bolton       37  39  40  42   0
Chelsea      65  71  71  72   0
Everton      40  44  45  45   0
Fulham       42  42  43  45   0
Liverpool    34  37  37  41   0
Man City     81  83  84  86   0
Man United   82  86  86  88   0
Newcastle    52  52  54  54   0
Norwich      48  49  49  52   0
QPR          38  39  40  41   0
Stoke        29  30  31  31   0
Sunderland   42  42  44  45   0
Swansea      34  35  39  39   0
Tottenham    59  61  65  66   0
West Brom    42  43  43  45   0
Wigan        32  33  37  38   0
Wolves       32  32  36  36   0

[20 rows x 39 columns]
GS=
              1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  34  \
Arsenal       0   1   7   9  13  14  16  16  18  21  ...  61  64  65  66  69
Aston Villa   0   3   3   4   5   6   8   9   9   9  ...  38  38  40  41  42
Birmingham    0   2   4   6   6   7   7   7   8  10  ...  29  31  32  34  35
Blackburn     0   1   2   3   4   5   7   7   7   8  ...  37  39  41  42  42
Blackpool     0   4   4   6   8   8   9  11  13  13  ...  41  43  43  43  44
Bolton        0   0   3   5   6   7   9  10  12  13  ...  43  46  46  48  50
Chelsea       0   6  12  14  17  21  21  23  23  25  ...  52  53  56  59  62
Everton       0   0   1   1   4   4   4   6   8   9  ...  33  35  37  40  42
Fulham        0   0   2   4   6   7   7   8   9  10  ...  31  32  35  36  37
Liverpool     0   1   1   2   2   4   6   7   7   9  ...  40  42  43  46  47
Man City      0   0   3   3   4   6   7   9  12  12  ...  45  45  50  51  53
Man United    0   3   5   8  11  14  16  16  18  20  ...  64  65  69  71  71
Newcastle     0   0   6   7   7   8   9  10  12  14  ...  43  43  47  47  47
Stoke         0   1   2   2   4   5   7   8   9  10  ...  32  36  37  39  40
Sunderland    0   2   2   3   4   5   7   7   7   8  ...  33  33  33  33  33
Tottenham     0   0   2   2   3   6   6   8  10  11  ...  39  42  45  47  48
West Brom     0   0   1   1   2   5   8   9  11  13  ...  43  45  47  50  51
West Ham      0   0   1   1   2   3   4   5   6   7  ...  36  36  36  36  36
Wigan         0   0   0   1   2   2   2   4   6   7  ...  24  26  26  26  29
Wolves        0   2   3   4   5   6   7   7   8   8  ...  37  38  39  40  41

             35  36  37  38  0
Arsenal      70  71  72  73   0
Aston Villa  43  44  45  47   0
Birmingham   35  36  37  37   0
Blackburn    42  43  44  45   0
Blackpool    45  45  46  50   0
Bolton       52  52  53  56   0
Chelsea      65  67  68  70   0
Everton      42  43  45  45   0
Fulham       40  43  45  47   0
Liverpool    52  55  60  60   0
Man City     54  55  56  59   0
Man United   72  72  74  75   0
Newcastle    48  48  50  52   0
Stoke        43  43  46  46   0
Sunderland   37  37  39  40   0
Tottenham    49  50  50  52   0
West Brom    53  55  56  57   0
West Ham     36  37  38  40   0
Wigan        31  33  34  37   0
Wolves       41  42  45  48   0

[20 rows x 39 columns]

GS=
              1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  34  \
Arsenal       0   6  10  11  13  17  23  29  31  33  ...  70  73  75  77  78
Aston Villa   0   3   5   6   7   9  10  11  12  13  ...  38  39  40  42  44
Birmingham    0   0   0   0   1   1   1   2   3   4  ...  27  28  29  30  31
Blackburn     0   1   2   2   2   2   4   7  10  10  ...  28  29  31  32  33
Bolton        0   0   0   2   5   6   8  10  13  16  ...  34  34  38  38  38
Burnley       0   0   1   2   3   3   6   9  11  13  ...  33  34  34  34  34
Chelsea       0   2   5   8  11  13  16  17  18  20  ...  70  71  72  79  81
Everton       0   0   2   3   6   7   8   9  11  13  ...  42  44  46  46  48
Fulham        0   0   0   2   3   4   6   8  10  13  ...  36  36  38  38  38
Hull          0   1   2   3   4   5   6   6   8  10  ...  33  35  35  35  36
Liverpool     0   1   5   9  10  14  18  24  24  24  ...  47  51  52  55  56
Man City      0   2   3   4   7  10  11  12  14  14  ...  45  48  51  56  56
Man United    0   1   1   1   3   6  10  14  16  18  ...  66  69  72  76  80
Portsmouth    0   0   0   1   2   2   2   2   3   4  ...  19  22  22  22  22
Stoke         0   2   4   4   5   6   7   7   8  10  ...  31  32  34  34  35
Sunderland    0   1   2   4   4   4   5   6   8  10  ...  32  35  36  36  36
Tottenham     0   2   7   9  11  12  12  12  14  16  ...  40  42  43  45  47
West Ham      0   1   2   2   4   5   7   8  10  12  ...  44  44  45  45  45
Wigan         0   2   2   2   3   4   4   4   5   6  ...  23  23  24  24  25
Wolves        0   0   0   0   0   1   3   5   7   8  ...  21  23  26  29  29

             35  36  37  38  0
Arsenal      79  80  80  81   0
Aston Villa  46  48  50  51   0
Birmingham   32  32  32  34   0
Blackburn    33  35  36  38   0
Bolton       38  38  40  40   0
Burnley      38  39  40  41   0
Chelsea      82  83  90  92   0
Everton      50  53  55  55   0
Fulham       39  42  45  45   0
Hull         36  36  36  38   0
Liverpool    56  59  63  63   0
Man City     56  56  59  59   0
Man United   80  81  84  85   0
Portsmouth   22  22  24  27   0
Stoke        35  35  35  36   0
Sunderland   36  38  39  39   0
Tottenham    48  49  50  51   0
West Ham     46  46  49  51   0
Wigan        25  28  30  32   0
Wolves       29  29  30  31   0

[20 rows x 39 columns]
GS=
                1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal         0   1   1   1   5   9  10  11  14  16  ...  42  46  48  52
Aston Villa     0   4   6   6   8  10  12  12  12  16  ...  46  46  48  50
Blackburn       0   3   4   5   6   7   8   8   8   9  ...  33  34  36  36
Bolton          0   3   3   3   4   5   5   8   8   8  ...  32  33  34  37
Chelsea         0   4   5   6   9  10  12  14  19  19  ...  50  50  50  54
Everton         0   2   4   4   7   9   9   9  10  11  ...  38  39  43  46
Fulham          0   1   3   5   6   6   6   7   9   9  ...  27  29  29  32
Hull            0   2   3   3   5   7   9  10  11  14  ...  33  33  33  34
Liverpool       0   1   3   3   5   5   7  10  13  14  ...  50  55  56  60
Man City        0   2   5   8   9  15  16  18  20  23  ...  40  40  40  41
Man United      0   1   2   3   5   7  11  12  14  18  ...  58  60  62  67
Middlesbrough   0   2   3   5   6   6   6   7   8   9  ...  22  22  23  26
Newcastle       0   1   2   2   3   4   5   7   9  11  ...  35  36  36  37
Portsmouth      0   0   0   3   5   5   7   9   9  10  ...  35  37  38  39
Stoke           0   1   4   5   7   7   7   8  10  10  ...  30  31  33  34
Sunderland      0   0   2   2   3   5   6   7   7   9  ...  30  30  30  31
Tottenham       0   1   2   3   4   4   4   4   5   7  ...  34  35  36  37
West Brom       0   0   1   1   4   5   6   7   7   7  ...  21  22  22  24
West Ham        0   2   2   6   8  11  13  14  14  14  ...  36  37  39  41
Wigan           0   1   1   6   7   7   9   9  11  11  ...  25  26  26  26

               34  35  36  37  38  0
Arsenal        56  58  61  62  62   0
Aston Villa    53  54  55  56  57   0
Blackburn      36  38  40  42  42   0
Bolton         40  41  41  41  42   0
Chelsea        54  54  57  61  63   0
Everton        46  47  49  49  52   0
Fulham         32  32  33  36  37   0
Hull           34  35  35  36  37   0
Liverpool      64  67  70  73  75   0
Man City       45  47  50  50  51   0
Man United     69  71  73  75  75   0
Middlesbrough  26  26  26  27  28   0
Newcastle      37  37  37  40  40   0
Portsmouth     39  39  39  39  42   0
Stoke          35  35  35  37  39   0
Sunderland     32  32  32  32  33   0
Tottenham      38  40  41  41  43   0
West Brom      26  29  29  32  32   0
West Ham       42  42  43  43  44   0
Wigan          26  27  28  29  29   0

[20 rows x 39 columns]
GS=
                1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal         0   1   2   5   8  11  12  13  16  17  ...  54  55  56  59
Aston Villa     0   1   1   3   3   5   9  13  14  15  ...  60  60  60  60
Birmingham      0   2   4   4   6   8   8   9   9  10  ...  35  36  37  40
Blackburn       0   1   2   3   4   4   6   8  10  12  ...  45  46  49  49
Bolton          0   1   2   3   4   7   7   7   8   9  ...  28  28  28  30
Chelsea         0   3   5   6   7   8   8   8   8   9  ...  50  54  56  57
Derby           0   2   2   2   2   2   2   3   4   4  ...  12  12  12  14
Everton         0   2   5   5   5   6   6   6   8  10  ...  45  45  46  46
Fulham          0   1   2   4   5   8  11  12  12  12  ...  24  25  25  27
Liverpool       0   1   3   5   5   5   6   8  10  11  ...  49  51  51  52
Man City        0   2   3   4   4   4   4   7  10  13  ...  35  37  37  38
Man United      0   0   1   1   2   3   4   5   7   8  ...  56  58  61  65
Middlesbrough   0   1   2   4   6   8   8  10  10  11  ...  27  28  29  29
Newcastle       0   3   5   6   6   9  10  13  16  17  ...  29  30  32  36
Portsmouth      0   2   3   6   6   7   7   8  15  17  ...  48  50  50  52
Reading         0   0   1   2   2   2   3   5   9  13  ...  35  36  38  38
Sunderland      0   1   3   3   3   3   5   7   9  11  ...  28  28  29  31
Tottenham       0   0   1   5   9  12  13  14  18  20  ...  59  63  65  66
West Ham        0   0   1   4   7   8   8   8  11  11  ...  28  30  31  32
Wigan           0   1   2   5   6   6   7   8   9   9  ...  27  28  29  29

               34  35  36  37  38  0
Arsenal        60  61  63  69  70   0
Aston Villa    64  70  75  77  77   0
Birmingham     40  41  42  44  44   0
Blackburn      50  51  52  53  56   0
Bolton         30  31  32  33  35   0
Chelsea        59  60  61  63  65   0
Derby          14  14  15  17  18   0
Everton        47  48  48  50  50   0
Fulham         28  30  30  33  35   0
Liverpool      53  56  58  60  61   0
Man City       38  40  43  45  45   0
Man United     67  69  70  71  75   0
Middlesbrough  31  32  32  34  36   0
Newcastle      39  39  41  43  43   0
Portsmouth     53  53  54  54  54   0
Reading        38  38  38  38  38   0
Sunderland     34  35  35  38  38   0
Tottenham      67  68  69  70  71   0
West Ham       32  32  34  36  37   0
Wigan          31  32  33  33  35   0

[20 rows x 39 columns]
GS=
                   1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal            0   0   0   1   2   4   6  10  14  14  ...  44  44  44  44
Aston Villa        0   1   3   5   6   6   8   9  10  11  ...  29  29  30  31
Blackburn          0   0   1   1   1   5   6   8   9   9  ...  40  41  42  45
Bolton             0   2   4   5   5   5   5   7   9  10  ...  40  41  42  45
Charlton           0   1   2   4   6   6   6   7   8   8  ...  29  31  32  32
Chelsea            0   3   4   6   8   9  11  12  13  15  ...  49  52  53  57
Everton            0   2   3   5   8  10  11  12  13  14  ...  34  35  36  40
Fulham             0   1   2   3   5   5   5   8  11  12  ...  29  29  29  30
Liverpool          0   2   2   2   2   4   6   6   7   7  ...  35  35  39  41
Man City           0   0   0   1   1   3   5   6   6   6  ...  25  25  28  31
Man United         0   5   8  10  11  11  12  14  17  19  ...  65  69  73  75
Middlesbrough      0   2   4   6   6   6   6   7   9  10  ...  33  33  33  37
Newcastle          0   0   1   3   5   5   6   6   7   7  ...  36  36  36  38
Portsmouth         0   3   3   7  11  12  12  13  15  16  ...  40  40  41  43
Reading            0   3   4   4   5   7   8   9   9   9  ...  44  44  44  45
Sheffield United   0   1   2   2   2   2   2   4   4   4  ...  24  25  25  28
Tottenham          0   0   2   2   2   2   2   4   5   6  ...  39  42  43  46
Watford            0   1   2   3   3   3   4   5   5   5  ...  17  18  18  19
West Ham           0   3   4   5   6   6   6   6   6   6  ...  18  20  22  22
Wigan              0   1   1   3   4   5   6  10  11  12  ...  32  32  32  32

                  34  35  36  37  38  0
Arsenal           46  49  51  54  55   0
Aston Villa       33  36  36  36  39   0
Blackburn         46  47  49  51  52   0
Bolton            48  49  50  52  53   0
Charlton          32  32  33  34  34   0
Chelsea           57  57  58  59  59   0
Everton           41  43  43  43  46   0
Fulham            31  31  32  33  34   0
Liverpool         41  43  45  46  46   0
Man City          31  32  33  33  33   0
Man United        76  80  81  82  82   0
Middlesbrough     38  38  39  41  42   0
Newcastle         40  41  41  41  41   0
Portsmouth        45  47  47  47  47   0
Reading           46  46  49  50  50   0
Sheffield United  31  34  35  36  36   0
Tottenham         48  51  53  55  56   0
Watford           23  24  25  25  27   0
West Ham          22  23  24  27  30   0
Wigan             33  36  36  36  36   0

[20 rows x 39 columns]

GS=
                1   2   3   4   5   6   7   8   9   10  ...  30  31  32  33  \
Arsenal         0   2   2   3   5   5   6   7   8   9  ...  44  47  47  47
Aston Villa     0   2   2   2   3   4   4   5   7   9  ...  27  27  28  28
Birmingham      0   0   1   1   1   4   4   6   6   6  ...  16  16  16  17
Blackburn       0   1   3   5   5   5   5   5   7   9  ...  39  42  43  44
Bolton          0   2   2   4   6   6   6   7   8   9  ...  37  37  37  37
Charlton        0   3   6   9  10  12  14  15  17  19  ...  38  38  41  44
Chelsea         0   1   2   6  10  12  14  16  18  23  ...  65  67  67  67
Everton         0   0   1   1   1   1   1   1   2   3  ...  27  31  32  33
Fulham          0   0   1   2   3   4   5   6   8  10  ...  46  47  48  49
Liverpool       0   0   0   2   4   5   6   6   8  10  ...  35  36  41  44
Man City        0   0   2   4   6   7   7   7   9  11  ...  36  37  37  37
Man United      0   2   4   6   6   7   8  11  12  13  ...  50  53  54  56
Middlesbrough   0   0   0   3   3   5   6   6   6   7  ...  38  39  40  40
Newcastle       0   0   0   0   0   1   4   7   7   7  ...  33  34  35  38
Portsmouth      0   0   1   2   3   4   5   6   6   7  ...  25  28  30  32
Sunderland      0   1   1   2   3   3   4   6   8   9  ...  23  23  23  25
Tottenham       0   2   4   4   4   4   5   6   9  11  ...  47  49  51  52
West Brom       0   0   2   2   4   5   6   7   7   9  ...  22  23  24  24
West Ham        0   3   4   8  12  12  13  14  16  18  ...  50  52  52  52
Wigan           0   0   1   3   4   5   7   8   9  10  ...  36  37  38  39

               34  35  36  37  38  0
Arsenal        48  51  54  57  60   0
Aston Villa    28  31  33  35  36   0
Birmingham     18  19  20  22  22   0
Blackburn      46  46  47  49  50   0
Bolton         37  37  37  37  38   0
Charlton       44  44  45  47  47   0
Chelsea        71  73  76  79  79   0
Everton        33  33  33  33  34   0
Fulham         50  51  52  54  55   0
Liverpool      47  49  50  51  54   0
Man City       38  39  40  41  42   0
Man United     58  58  60  60  60   0
Middlesbrough  42  42  42  42  43   0
Newcastle      40  43  47  51  51   0
Portsmouth     33  34  35  37  39   0
Sunderland     26  27  27  27  29   0
Tottenham      54  55  56  57  58   0
West Brom      24  25  25  25  25   0
West Ham       53  54  54  55  56   0
Wigan          40  41  44  44  45   0

[20 rows x 39 columns]

### GET RESPECTIVE POINTS:

In [18]:
def get_points(R):
    P=3*(R=='W')+1*(R=='D')+0*(R=='L')
    return P
    

def get_cuml_points(playing_stat,matchres):
    Team=playing_stat.groupby('HomeTeam').mean().T.columns
    L=(len(Team)-1)*2+1

    #matchres_points = matchres.apply(get_points)
    matchres_points = matchres.applymap(get_points)

    for i in range(2,L):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
    
    
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(len(Team))])
    return matchres_points


def get_matchres(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    Team=playing_stat.groupby('HomeTeam').mean().T.columns
    L=(len(Team)-1)*2+1
    
    for i in Team:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
    #Padding        
    teams=Padding('-',Team,teams,L)
    
    return pd.DataFrame(data=teams, index = [i for i in range(1,L)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)    
    #print('teams:\n',matchres)
    cum_pts = get_cuml_points(playing_stat,matchres)
    HTP = []
    ATP = []

    for i in range(len(playing_stat)):
        j=playing_stat.loc[i]['MW'] # -1 #before playing match week
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat
    
# Apply to each dataset
playing_statistics_1 = get_agg_points(playing_statistics_1)
playing_statistics_1.groupby('HomeTeam').mean().T

HomeTeam,Arsenal,Aston Villa,Bournemouth,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Leicester,Liverpool,Man City,Man United,Newcastle,Norwich,Sheffield United,Southampton,Tottenham,Watford,West Ham,Wolves
FTHG,1.250000,1.272727,0.727273,1.083333,0.666667,1.818182,0.909091,0.818182,1.727273,1.666667,3.000000,0.818182,0.833333,0.833333,1.090909,1.333333,1.272727,0.833333,1.000000,1.363636
FTAG,1.000000,1.636364,1.909091,1.083333,1.666667,1.181818,2.090909,1.363636,1.272727,1.583333,1.500000,1.818182,1.333333,1.250000,1.727273,1.750000,0.909091,1.083333,0.909091,1.909091
HTHG,0.583333,0.636364,0.545455,0.416667,0.166667,1.181818,0.272727,0.545455,0.545455,0.833333,1.333333,0.454545,0.583333,0.250000,0.272727,0.416667,0.818182,0.500000,0.636364,0.454545
HTAG,0.166667,0.727273,1.181818,0.333333,0.750000,0.454545,1.090909,0.636364,0.909091,0.416667,0.500000,0.727273,0.833333,0.500000,0.909091,0.833333,0.363636,0.416667,0.636364,1.090909
HS,10.500000,13.272727,8.181818,11.083333,8.583333,15.636364,7.909091,12.090909,11.909091,14.250000,18.166667,11.909091,7.833333,10.333333,9.000000,12.583333,8.272727,8.916667,10.363636,12.818182
AS,12.083333,15.090909,13.181818,10.250000,13.833333,13.090909,12.454545,14.454545,10.727273,12.666667,17.250000,13.363636,13.416667,11.833333,11.454545,14.833333,12.454545,12.500000,9.818182,10.909091
HST,3.500000,5.272727,2.363636,4.083333,2.083333,5.454545,2.818182,3.090909,4.818182,5.333333,7.250000,4.545455,2.500000,3.500000,2.636364,5.166667,4.181818,2.583333,4.090909,4.181818
AST,3.916667,6.272727,5.181818,3.833333,5.666667,3.363636,4.272727,4.454545,4.181818,3.750000,5.250000,5.000000,4.416667,3.750000,3.909091,5.250000,4.363636,4.416667,3.181818,5.181818
HF,11.083333,11.363636,9.636364,10.750000,10.416667,9.545455,10.454545,12.818182,10.272727,7.083333,10.500000,9.818182,8.000000,10.083333,11.545455,12.750000,9.272727,10.166667,8.818182,12.000000
AF,10.166667,10.727273,11.454545,9.583333,7.666667,9.636364,9.454545,11.272727,9.545455,9.166667,10.000000,10.090909,9.750000,9.333333,12.090909,8.500000,8.818182,8.833333,8.545455,11.272727
HC,5.583333,4.545455,4.818182,3.750000,3.583333,5.272727,3.181818,6.545455,5.000000,5.000000,6.666667,5.090909,2.250000,4.333333,4.090909,5.833333,3.545455,3.750000,4.909091,6.272727
AC,5.666667,5.181818,6.000000,4.750000,5.333333,6.090909,4.363636,5.727273,5.909091,6.750000,6.666667,4.636364,5.500000,5.916667,5.636364,6.750000,5.727273,6.500000,3.636364,3.818182
HY,2.416667,1.636364,2.000000,1.666667,2.166667,1.818182,1.272727,2.000000,1.272727,0.833333,1.666667,1.909091,1.250000,2.083333,2.363636,1.750000,2.272727,2.416667,1.363636,1.818182
AY,1.750000,1.727273,1.636364,1.583333,1.333333,1.181818,1.636364,1.727273,1.454545,1.666667,1.166667,1.727273,1.333333,2.250000,2.090909,1.000000,1.272727,1.750000,1.909091,1.363636
HR,0.083333,0.090909,0.000000,0.083333,0.000000,0.000000,0.000000,0.181818,0.000000,0.083333,0.166667,0.000000,0.083333,0.000000,0.000000,0.000000,0.090909,0.250000,0.090909,0.181818
AR,0.000000,0.000000,0.090909,0.083333,0.000000,0.000000,0.000000,0.090909,0.000000,0.000000,0.166667,0.090909,0.000000,0.000000,0.090909,0.000000,0.090909,0.083333,0.090909,0.000000
B365H,2.486667,7.066364,4.168182,6.126667,4.515000,2.658182,4.756364,3.752727,2.980909,1.261667,1.340000,2.583636,7.116667,6.619167,5.483636,6.016667,2.592727,4.883333,2.950000,4.580909
B365D,4.583333,4.170909,3.527273,4.800000,4.783333,4.234545,3.836364,4.584545,3.840909,4.941667,4.012500,3.631818,3.575000,4.317500,4.190909,4.544167,3.698182,3.658333,3.420909,5.140909
B365A,3.980833,2.154545,1.987273,4.834167,3.936667,3.671818,2.849091,2.930000,3.326364,3.747500,2.323333,1.903636,1.845000,2.857500,4.081818,2.170000,2.848182,3.344167,2.527273,6.156364
BWH,2.488333,6.775455,3.963636,6.477500,4.481667,2.650909,4.631818,3.763636,2.992727,1.276667,1.347500,2.522727,7.104167,6.590833,5.416364,5.920833,2.568182,4.844167,2.918182,4.427273
BWD,4.558333,4.127273,3.536364,4.720833,4.704167,4.140909,3.809091,4.581818,3.768182,4.766667,4.054167,3.613636,3.562500,4.458333,4.150000,4.345833,3.652727,3.683333,3.390909,5.140909
BWA,3.872500,2.154545,2.000909,4.880833,3.898333,3.713636,2.884545,2.956364,3.194545,3.579167,2.352500,1.924545,1.851667,2.814167,4.290909,2.214167,2.916364,3.347500,2.508182,5.942727
IWH,2.474167,6.809091,3.940909,6.125000,4.425000,2.720000,4.454545,3.670000,2.986364,1.285000,1.367500,2.540909,6.970833,6.333333,5.250000,6.147500,2.618182,4.645833,2.904545,4.292727
IWD,4.483333,4.054545,3.490909,4.691667,4.612500,4.077273,3.763636,4.377273,3.650000,4.720833,4.033333,3.577273,3.508333,4.333333,4.081818,4.308333,3.595455,3.670833,3.409091,5.027273
IWA,3.657500,2.156364,2.013636,4.785833,3.897500,3.600000,2.857273,2.875455,3.342727,3.565000,2.360000,1.918182,1.865000,2.827500,4.169091,2.196667,2.827273,3.181667,2.504545,5.935455
WHH,2.555000,7.427273,4.177273,6.766667,4.656667,2.722727,4.847273,3.881818,3.070909,1.275000,1.347500,2.693636,7.550000,7.098333,5.414545,7.141667,2.668182,5.287500,2.957273,5.049091
WHD,4.433333,4.045455,3.518182,4.612500,4.708333,4.104545,3.795455,4.600000,3.759091,4.787500,4.029167,3.595455,3.545833,4.385833,4.127273,4.350000,3.686364,3.633333,3.386364,5.122727
WHA,4.075833,2.162727,2.015455,5.170833,4.156667,3.765455,2.919091,2.888182,3.332727,3.629167,2.353333,1.913636,1.853333,2.877500,4.301818,2.206667,2.971818,3.268333,2.502727,6.235455
VCH,2.552500,7.812727,4.098182,6.734167,4.787500,2.690909,4.977273,3.997273,3.051818,1.282500,1.350000,2.716364,7.629167,7.445833,5.780000,7.559167,2.720909,5.390000,3.009091,4.727273
VCD,4.512500,4.113636,3.540909,4.745833,4.800000,4.119091,3.868182,4.622727,3.857273,4.841667,4.050000,3.618182,3.575000,4.485833,4.213636,4.458333,3.700000,3.694167,3.404545,5.204545
VCA,4.261667,2.187273,2.030000,5.205833,4.211667,3.782727,2.992727,2.950000,3.523636,3.876667,2.367500,1.943636,1.876667,2.899167,4.508182,2.225833,2.986364,3.366667,2.578182,6.591818
MW,12.500000,11.363636,11.272727,12.333333,12.583333,11.545455,11.272727,11.545455,11.454545,12.416667,12.666667,11.272727,12.750000,12.666667,11.090909,12.666667,11.363636,12.333333,12.090909,11.363636
HTGS,16.083333,14.000000,12.272727,13.250000,14.833333,20.363636,8.909091,10.909091,22.545455,27.333333,34.333333,15.000000,10.583333,12.500000,11.363636,12.833333,18.454545,7.166667,14.000000,13.909091
ATGS,17.166667,16.909091,14.363636,15.833333,18.833333,12.545455,16.818182,15.454545,14.090909,16.166667,16.666667,13.909091,17.583333,14.250000,12.727273,15.500000,14.909091,16.583333,14.363636,15.909091
HTGC,11.583333,16.363636,19.454545,16.500000,17.166667,13.363636,18.454545,15.181818,12.272727,16.083333,16.166667,13.363636,17.750000,18.166667,12.818182,20.750000,13.454545,13.416667,12.090909,15.909091
ATGC,16.833333,15.272727,12.818182,16.666667,16.666667,16.818182,13.818182,13.636364,15.454545,16.333333,17.916667,15.090909,16.750000,16.583333,13.363636,16.500000,14.727273,16.833333,15.272727,14.272727
HTP,17.583333,10.636364,12.909091,14.250000,15.333333,20.272727,15.454545,13.272727,24.272727,35.500000,26.750000,16.000000,15.083333,9.000000,15.363636,12.666667,16.090909,8.416667,13.818182,15.454545
ATP,17.666667,17.727273,16.545455,16.250000,19.000000,13.545455,16.000000,14.727273,14.909091,16.083333,17.666667,14.181818,18.666667,15.833333,13.363636,16.333333,16.909091,16.916667,16.636364,14.727273

In [19]:
playing_statistics_2 = get_agg_points(playing_statistics_2)
playing_statistics_3 = get_agg_points(playing_statistics_3)
playing_statistics_4 = get_agg_points(playing_statistics_4)
playing_statistics_5 = get_agg_points(playing_statistics_5)
playing_statistics_6 = get_agg_points(playing_statistics_6)
playing_statistics_7 = get_agg_points(playing_statistics_7)
playing_statistics_8 = get_agg_points(playing_statistics_8)
playing_statistics_9 = get_agg_points(playing_statistics_9)
playing_statistics_10 = get_agg_points(playing_statistics_10)
playing_statistics_11 = get_agg_points(playing_statistics_11)
playing_statistics_12 = get_agg_points(playing_statistics_12)
playing_statistics_13 = get_agg_points(playing_statistics_13)
playing_statistics_14 = get_agg_points(playing_statistics_14)
playing_statistics_15 = get_agg_points(playing_statistics_15)

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

GET TEAM FORM: TEAM HISTORY

In [20]:
def get_num_previous_ftr(playing_stat,num,L):
    
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,L):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1 
    return form_final

def add_num_previous_ftr(playing_stat,num,L,half_team_number):
    form = get_num_previous_ftr(playing_stat,num,L)
    h = ['M' for i in range(num * half_team_number)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 10)]
    
    j = num
    for i in range((num*10),len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 10) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat


def add_num_previous_ftr_to_df(playing_statistics):
    Half_Team=int(len(playing_statistics.groupby('HomeTeam').mean().T.columns)/2)
    L=(2*Half_Team-1)*2+1
    playing_statistics = add_num_previous_ftr(playing_statistics,1,L,Half_Team)
    playing_statistics = add_num_previous_ftr(playing_statistics,2,L,Half_Team)
    playing_statistics = add_num_previous_ftr(playing_statistics,3,L,Half_Team)
    playing_statistics = add_num_previous_ftr(playing_statistics,4,L,Half_Team)
    playing_statistics = add_num_previous_ftr(playing_statistics,5,L,Half_Team)
    return playing_statistics    

#Make changes to df
playing_statistics_1 = add_num_previous_ftr_to_df(playing_statistics_1)
playing_statistics_1.head(56)

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,HST,...,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,Liverpool,Norwich,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
1,West Ham,Man City,0,0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
2,Bournemouth,Sheffield United,0,0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
3,Burnley,Southampton,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
4,Crystal Palace,Everton,0,0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
5,Watford,Brighton,0,0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
6,Tottenham,Aston Villa,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
7,Leicester,Wolves,0,0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
8,Newcastle,Arsenal,0,0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
9,Man United,Chelsea,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
10,Arsenal,Burnley,1,3,H,0.0,0.0,8.0,10.0,2.0,...,W,W,M,M,M,M,M,M,M,M
11,Aston Villa,Bournemouth,1,1,A,1.0,0.0,7.0,13.0,4.0,...,L,D,M,M,M,M,M,M,M,M
12,Brighton,West Ham,3,0,D,1.0,0.0,5.0,5.0,3.0,...,W,L,M,M,M,M,M,M,M,M
13,Everton,Watford,0,0,H,0.0,0.0,10.0,11.0,3.0,...,D,L,M,M,M,M,M,M,M,M
14,Norwich,Newcastle,1,0,H,0.0,0.0,12.0,9.0,5.0,...,L,L,M,M,M,M,M,M,M,M
15,Southampton,Liverpool,0,4,A,0.0,4.0,11.0,15.0,3.0,...,L,W,M,M,M,M,M,M,M,M
16,Man City,Tottenham,5,3,D,1.0,0.0,14.0,31.0,9.0,...,W,W,M,M,M,M,M,M,M,M
17,Sheffield United,Crystal Palace,1,0,H,0.0,0.0,8.0,6.0,3.0,...,D,D,M,M,M,M,M,M,M,M
18,Chelsea,Leicester,0,0,D,0.0,0.0,18.0,15.0,7.0,...,L,D,M,M,M,M,M,M,M,M
19,Wolves,Man United,0,4,D,0.0,1.0,8.0,11.0,2.0,...,D,W,M,M,M,M,M,M,M,M
20,Aston Villa,Everton,1,1,H,0.0,1.0,22.0,12.0,7.0,...,L,W,L,D,M,M,M,M,M,M
21,Norwich,Chelsea,3,1,A,1.0,1.0,15.0,14.0,8.0,...,W,D,L,L,M,M,M,M,M,M
22,Brighton,Southampton,1,1,A,0.0,0.0,16.0,14.0,4.0,...,D,L,W,L,M,M,M,M,M,M
23,Man United,Crystal Palace,1,0,A,1.0,0.0,9.0,6.0,2.0,...,D,L,W,D,M,M,M,M,M,M
24,Sheffield United,Leicester,1,1,A,0.0,0.0,15.0,12.0,3.0,...,W,D,D,D,M,M,M,M,M,M
25,Watford,West Ham,0,1,A,0.0,0.0,8.0,8.0,2.0,...,L,D,L,L,M,M,M,M,M,M
26,Liverpool,Arsenal,2,2,H,1.0,1.0,15.0,16.0,6.0,...,W,W,W,W,M,M,M,M,M,M
27,Bournemouth,Man City,2,2,A,2.0,2.0,12.0,30.0,4.0,...,W,D,D,W,M,M,M,M,M,M
28,Tottenham,Newcastle,2,1,A,1.0,0.0,3.0,10.0,2.0,...,D,L,W,L,M,M,M,M,M,M
29,Wolves,Burnley,1,1,D,0.0,1.0,6.0,18.0,2.0,...,D,L,D,W,M,M,M,M,M,M
30,Southampton,Man United,2,1,D,0.0,0.0,12.0,22.0,4.0,...,W,L,L,D,L,W,M,M,M,M
31,Chelsea,Sheffield United,3,1,D,2.0,0.0,23.0,8.0,8.0,...,W,L,D,W,L,D,M,M,M,M
32,Crystal Palace,Aston Villa,2,2,H,1.0,1.0,5.0,7.0,3.0,...,W,W,L,L,D,L,M,M,M,M
33,Leicester,Bournemouth,2,1,H,1.0,1.0,10.0,10.0,2.0,...,W,L,D,W,D,D,M,M,M,M
34,Man City,Brighton,3,0,H,2.0,0.0,19.0,12.0,5.0,...,W,L,D,D,W,W,M,M,M,M
35,Newcastle,Watford,1,1,D,1.0,1.0,8.0,23.0,3.0,...,W,L,L,L,L,L,M,M,M,M
36,West Ham,Norwich,3,2,H,1.0,2.0,16.0,6.0,10.0,...,W,L,D,W,L,L,M,M,M,M
37,Burnley,Liverpool,1,3,A,1.0,1.0,13.0,25.0,4.0,...,D,W,L,W,W,W,M,M,M,M
38,Everton,Wolves,0,1,H,0.0,0.0,12.0,17.0,1.0,...,L,D,W,D,D,D,M,M,M,M
39,Arsenal,Tottenham,1,0,D,0.0,0.0,9.0,17.0,3.0,...,L,L,W,D,W,W,M,M,M,M
40,Liverpool,Newcastle,3,1,H,2.0,1.0,15.0,13.0,7.0,...,W,D,W,W,W,L,W,L,M,M
41,Brighton,Burnley,0,0,D,0.0,0.0,6.0,7.0,2.0,...,L,L,L,D,D,L,W,W,M,M
42,Man United,Leicester,1,3,H,1.0,2.0,21.0,13.0,8.0,...,D,W,L,W,D,D,W,D,M,M
43,Sheffield United,Southampton,2,1,A,0.0,0.0,8.0,10.0,2.0,...,D,D,L,W,W,L,D,L,M,M
44,Tottenham,Crystal Palace,2,1,H,2.0,0.0,13.0,22.0,9.0,...,D,W,L,W,D,L,W,D,M,M
45,Wolves,Chelsea,2,2,A,1.0,2.0,8.0,13.0,5.0,...,L,D,D,W,D,D,D,L,M,M
46,Norwich,Man City,0,4,H,0.0,2.0,8.0,15.0,3.0,...,L,W,L,W,W,D,L,W,M,M
47,Bournemouth,Everton,1,3,H,1.0,2.0,8.0,15.0,2.0,...,L,W,L,L,W,W,D,D,M,M
48,Watford,Arsenal,1,2,D,1.0,1.0,13.0,26.0,3.0,...,D,D,L,L,L,W,L,W,M,M
49,Aston Villa,West Ham,0,2,D,0.0,1.0,10.0,18.0,2.0,...,L,W,W,W,L,D,L,L,M,M
50,Southampton,Bournemouth,1,3,A,0.0,1.0,11.0,13.0,7.0,...,W,W,D,L,W,L,L,W,L,D
51,Leicester,Tottenham,0,4,H,0.0,4.0,9.0,13.0,3.0,...,L,W,W,D,W,L,D,D,D,W
52,Burnley,Norwich,1,3,H,0.0,2.0,7.0,7.0,1.0,...,D,W,L,L,D,L,L,W,W,L
53,Everton,Sheffield United,1,0,A,1.0,0.0,14.0,17.0,5.0,...,L,L,W,D,L,L,W,W,D,D
54,Man City,Watford,2,2,H,1.0,0.0,25.0,31.0,8.0,...,L,D,W,D,W,L,D,L,W,L
55,Newcastle,Brighton,1,1,D,1.0,0.0,8.0,14.0,1.0,...,L,D,D,L,W,L,L,D,L,W

In [21]:
# Make changes to df

playing_statistics_2 = add_num_previous_ftr_to_df(playing_statistics_2)
playing_statistics_3 = add_num_previous_ftr_to_df(playing_statistics_3)
playing_statistics_4 = add_num_previous_ftr_to_df(playing_statistics_4)
playing_statistics_5 = add_num_previous_ftr_to_df(playing_statistics_5)
playing_statistics_6 = add_num_previous_ftr_to_df(playing_statistics_6)
playing_statistics_7 = add_num_previous_ftr_to_df(playing_statistics_7)
playing_statistics_8 = add_num_previous_ftr_to_df(playing_statistics_8)
playing_statistics_9 = add_num_previous_ftr_to_df(playing_statistics_9)
playing_statistics_10 = add_num_previous_ftr_to_df(playing_statistics_10)
playing_statistics_11 = add_num_previous_ftr_to_df(playing_statistics_11)
playing_statistics_12 = add_num_previous_ftr_to_df(playing_statistics_12)
playing_statistics_13 = add_num_previous_ftr_to_df(playing_statistics_13)
playing_statistics_14 = add_num_previous_ftr_to_df(playing_statistics_14)
playing_statistics_15 = add_num_previous_ftr_to_df(playing_statistics_15)

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
'''# Rearranging columns
cols = ['Date', 'HomeTeam', 'AwayTeam', 'MW', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',
        'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5' ]

playing_statistics_1 = playing_statistics_1[cols]
playing_statistics_2 = playing_statistics_2[cols]
playing_statistics_3 = playing_statistics_3[cols]
playing_statistics_4 = playing_statistics_4[cols]
playing_statistics_5 = playing_statistics_5[cols]
playing_statistics_6 = playing_statistics_6[cols]
playing_statistics_7 = playing_statistics_7[cols]
playing_statistics_8 = playing_statistics_8[cols]
playing_statistics_9 = playing_statistics_9[cols]
playing_statistics_10 = playing_statistics_10[cols]
playing_statistics_11 = playing_statistics_11[cols]
playing_statistics_12 = playing_statistics_12[cols]
playing_statistics_13 = playing_statistics_13[cols]
playing_statistics_14 = playing_statistics_14[cols]
playing_statistics_15 = playing_statistics_15[cols]'''

"# Rearranging columns\ncols = ['Date', 'HomeTeam', 'AwayTeam', 'MW', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',\n        'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5' ]\n\nplaying_statistics_1 = playing_statistics_1[cols]\nplaying_statistics_2 = playing_statistics_2[cols]\nplaying_statistics_3 = playing_statistics_3[cols]\nplaying_statistics_4 = playing_statistics_4[cols]\nplaying_statistics_5 = playing_statistics_5[cols]\nplaying_statistics_6 = playing_statistics_6[cols]\nplaying_statistics_7 = playing_statistics_7[cols]\nplaying_statistics_8 = playing_statistics_8[cols]\nplaying_statistics_9 = playing_statistics_9[cols]\nplaying_statistics_10 = playing_statistics_10[cols]\nplaying_statistics_11 = playing_statistics_11[cols]\nplaying_statistics_12 = playing_statistics_12[cols]\nplaying_statistics_13 = playing_statistics_13[cols]\nplaying_statistics_14 = playing_statistics_14[cols]\nplaying_statistics_15 = playing_statistics_15[cols]"

In [23]:
playing_statistics_6

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,HST,...,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,Arsenal,Crystal Palace,0.0,0.0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
1,Leicester,Everton,0.0,0.0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
2,Man United,Swansea,0.0,0.0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
3,QPR,Hull,0.0,0.0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
4,Stoke,Aston Villa,0.0,0.0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Hull,Man United,0.0,1.0,D,0.0,1.0,14.0,12.0,2.0,...,L,D,L,W,L,L,W,L,W,L
376,Leicester,QPR,0.0,2.0,H,0.0,0.0,11.0,8.0,0.0,...,D,W,W,L,W,L,L,D,W,L
377,Man City,Southampton,4.0,6.0,H,2.0,5.0,22.0,18.0,11.0,...,W,W,W,L,W,L,W,D,W,L
378,Newcastle,West Ham,1.0,1.0,H,1.0,0.0,22.0,13.0,8.0,...,L,L,D,L,L,W,L,D,L,L
379,Stoke,Liverpool,0.0,1.0,H,0.0,1.0,11.0,18.0,3.0,...,D,L,W,D,L,W,D,L,W,D

Get Last Year's Position as also an independent variable:

In [24]:
Standings = pd.read_csv(loc + "EPLStandings.csv")
Standings.set_index(['Team'], inplace=True)
#Standings.drop('Team',axis=0)
Standings = Standings.fillna(18)

In [25]:
def get_last(playing_stat, Standings, year):
    HomeTeamLP = []
    AwayTeamLP = []
    for i in range(len(playing_stat)):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HomeTeamLP.append(Standings.loc[ht][year])
        AwayTeamLP.append(Standings.loc[at][year])
    playing_stat['HomeTeamLP'] = HomeTeamLP
    playing_stat['AwayTeamLP'] = AwayTeamLP
    return playing_stat

playing_statistics_1 = get_last(playing_statistics_1, Standings, '2019')

In [26]:
playing_statistics_2 = get_last(playing_statistics_2, Standings, '2018')
playing_statistics_3 = get_last(playing_statistics_3, Standings, '2017')
playing_statistics_4 = get_last(playing_statistics_4, Standings, '2016')
playing_statistics_5 = get_last(playing_statistics_5, Standings, '2015')
playing_statistics_6 = get_last(playing_statistics_6, Standings, '2014')
playing_statistics_7 = get_last(playing_statistics_7, Standings, '2013')
playing_statistics_8 = get_last(playing_statistics_8, Standings, '2012')
playing_statistics_9 = get_last(playing_statistics_9, Standings, '2011')
playing_statistics_10 = get_last(playing_statistics_10, Standings, '2010')
playing_statistics_11 = get_last(playing_statistics_11, Standings, '2009')
playing_statistics_12 = get_last(playing_statistics_12, Standings, '2008')
playing_statistics_13 = get_last(playing_statistics_13, Standings, '2007')
playing_statistics_14 = get_last(playing_statistics_14, Standings, '2006')
playing_statistics_15 = get_last(playing_statistics_15, Standings, '2005')

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [27]:
playing_statistics_1

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,HST,...,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HomeTeamLP,AwayTeamLP
0,Liverpool,Norwich,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,2.0,18.0
1,West Ham,Man City,0,0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,10.0,1.0
2,Bournemouth,Sheffield United,0,0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,14.0,18.0
3,Burnley,Southampton,0,0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,15.0,16.0
4,Crystal Palace,Everton,0,0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,12.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Southampton,Wolves,2,1,NaN,1.0,1.0,16.0,9.0,10.0,...,W,L,D,L,W,W,W,W,16.0,7.0
225,West Ham,Everton,0,1,NaN,0.0,1.0,7.0,14.0,2.0,...,L,L,W,W,L,W,L,D,10.0,8.0
226,Newcastle,Chelsea,1,3,NaN,1.0,2.0,5.0,18.0,1.0,...,L,D,L,W,L,L,W,W,13.0,3.0
227,Burnley,Leicester,0,1,NaN,0.0,1.0,7.0,5.0,2.0,...,L,W,L,W,L,L,W,L,15.0,9.0
228,Liverpool,Man United,1,4,NaN,1.0,1.0,13.0,13.0,7.0,...,W,L,W,W,W,W,W,L,2.0,6.0

In [28]:
#playing_statistics_13.dropna(inplace=True)
#playing_statistics_13.isnull().sum().sum()

FINAL DATAFRAME


Data concatenation

In [29]:
playing_stat = pd.concat([playing_statistics_15,
                          playing_statistics_14,
                          playing_statistics_13,
                          playing_statistics_12,
                          playing_statistics_11,
                          playing_statistics_10,
                          playing_statistics_9,
                          playing_statistics_8,
                          playing_statistics_7,
                          playing_statistics_6,
                          playing_statistics_5,
                          playing_statistics_4,
                          playing_statistics_3,
                          playing_statistics_2], ignore_index=True)


playing_stat

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,HST,...,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HomeTeamLP,AwayTeamLP
0,Aston Villa,Bolton,0.0,0.0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,10.0,6.0
1,Everton,Man United,0.0,0.0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,4.0,3.0
2,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,13.0,12.0
3,Man City,West Brom,0.0,0.0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,8.0,17.0
4,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,M,7.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5315,Liverpool,Wolves,3.0,1.0,H,2.0,0.0,11.0,19.0,4.0,...,W,W,W,W,W,D,W,L,4.0,18.0
5316,Man United,Cardiff,1.0,2.0,A,1.0,1.0,23.0,18.0,7.0,...,D,L,L,L,L,W,W,L,2.0,18.0
5317,Southampton,Huddersfield,0.0,1.0,D,0.0,0.0,11.0,7.0,1.0,...,D,L,D,L,L,L,W,L,17.0,16.0
5318,Tottenham,Everton,0.0,2.0,D,0.0,2.0,11.0,20.0,5.0,...,L,D,W,W,L,L,W,W,3.0,8.0
5319,Watford,West Ham,0.0,3.0,A,0.0,1.0,15.0,17.0,3.0,...,L,W,D,D,W,L,L,L,14.0,13.0

In [30]:
playing_stat.dropna(inplace=True)
print(playing_stat.isnull().sum().sum())

0

In [31]:
playing_stat = pd.concat([playing_stat, playing_statistics_1],ignore_index=True)
print(playing_statistics_1.isnull().sum().sum())
print(playing_stat.isnull().sum().sum())

10
10

# Teams Id Series

In [32]:
teams=list(playing_stat.groupby('HomeTeam').mean().T.columns) 
l2=list(playing_stat.groupby('AwayTeam').mean().T.columns)
teams.extend(item for item in l2 if (item not in teams) )
teams_id=pd.Series(data=range(len(teams)),index=teams)

In [33]:
l1=[1,-2,3]
l2=[3,-5,4]
l1.extend(item for item in l2 if (item not in l1) )
l1.extend([1])
l1

[1, -2, 3, -5, 4, 1]

# Direct Confrentation

We use the information on the `` direct confrontation '' because for certain teams which have a weak history but which have a strong history of direct confrontation with the confronted team and which explain the exploitation of the couple well (HomeTeam, AwayTeam) and we avoid the dummies on this couple which increases the size of the data

In [34]:
def dc_points(P):
    R=1*(P=='H')-1*(P=='A')+0
    return R

def get_direct_confrentation(playing_stat):
    DC=[0]
    for i in range (1,len(playing_stat)):

        playing_stat_copy=playing_stat.iloc[:i].copy()
        ht=playing_stat.loc[i]['HomeTeam']
        at=playing_stat.loc[i]['AwayTeam']
        C1=((playing_stat['HomeTeam']==ht) & (playing_stat['AwayTeam']==at))
        C2=((playing_stat['HomeTeam']==at) & (playing_stat['AwayTeam']==ht))
        if any(C1 | C2):
            playing_stat_copy2=playing_stat_copy[C1 | C2]
            R=playing_stat_copy2['FTR'].apply(dc_points).sum()
            DC.extend([R])
        else:
            DC.extend([0])
    playing_stat['DC']=DC
    return playing_stat

In [35]:
playing_stat=get_direct_confrentation(playing_stat)
playing_stat[((playing_stat['HomeTeam']=='Man United') & (playing_stat['AwayTeam']=='Everton')) | ((playing_stat['HomeTeam']=='Everton') & (playing_stat['AwayTeam']=='Man United'))]

C:\Users\hsanb\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HS,AS,HST,...,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HomeTeamLP,AwayTeamLP,DC
1,Everton,Man United,0.0,0.0,A,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,4.0,3.0,0
154,Man United,Everton,1.0,1.0,D,1.0,1.0,21.0,7.0,12.0,...,W,W,W,W,L,W,W,3.0,4.0,-1
523,Man United,Everton,1.0,1.0,H,1.0,0.0,8.0,9.0,5.0,...,W,W,L,W,L,W,D,2.0,11.0,-1
730,Everton,Man United,0.0,4.0,A,0.0,0.0,10.0,18.0,2.0,...,D,D,W,W,L,D,W,11.0,2.0,0
827,Man United,Everton,1.0,2.0,H,1.0,1.0,5.0,12.0,3.0,...,W,W,D,L,W,W,D,1.0,6.0,-1
1110,Everton,Man United,1.0,1.0,D,1.0,1.0,7.0,18.0,3.0,...,W,L,W,D,W,W,D,5.0,1.0,0
1262,Man United,Everton,1.0,1.0,H,1.0,0.0,17.0,7.0,10.0,...,D,W,W,W,W,W,W,1.0,5.0,0
1530,Man United,Everton,0.0,0.0,H,0.0,0.0,21.0,11.0,10.0,...,W,L,D,W,L,D,D,1.0,5.0,1
1663,Everton,Man United,2.0,5.0,H,1.0,2.0,7.0,21.0,5.0,...,W,W,W,W,W,W,D,5.0,1.0,2
1819,Everton,Man United,0.0,3.0,D,0.0,1.0,15.0,18.0,9.0,...,D,L,W,M,M,M,M,8.0,2.0,3
2119,Man United,Everton,0.0,2.0,H,0.0,0.0,18.0,17.0,8.0,...,W,W,D,W,W,L,D,2.0,8.0,3
2258,Everton,Man United,0.0,1.0,A,0.0,0.0,18.0,12.0,11.0,...,D,L,W,L,D,L,W,7.0,1.0,4
2511,Man United,Everton,4.0,4.0,D,2.0,1.0,24.0,17.0,16.0,...,W,W,D,W,W,W,W,1.0,7.0,3
2557,Everton,Man United,0.0,0.0,H,0.0,0.0,0.0,0.0,0.0,...,M,M,M,M,M,M,M,7.0,2.0,3
2806,Man United,Everton,1.0,3.0,H,0.0,1.0,13.0,22.0,8.0,...,W,D,D,W,D,W,W,2.0,7.0,4
3062,Man United,Everton,2.0,4.0,A,1.0,1.0,8.0,22.0,3.0,...,D,W,D,W,D,W,W,1.0,6.0,5
3271,Everton,Man United,2.0,0.0,H,0.0,0.0,17.0,9.0,5.0,...,W,W,W,W,L,W,W,6.0,1.0,4
3375,Man United,Everton,2.0,1.0,H,2.0,0.0,8.0,11.0,3.0,...,L,W,W,D,L,D,D,7.0,5.0,5
3644,Everton,Man United,1.0,0.0,H,1.0,0.0,21.0,15.0,8.0,...,W,W,W,W,W,W,W,5.0,7.0,6
3768,Everton,Man United,1.0,0.0,A,1.0,0.0,14.0,9.0,4.0,...,W,D,W,W,W,D,L,11.0,4.0,7
3996,Man United,Everton,1.0,1.0,H,0.0,1.0,10.0,12.0,2.0,...,L,L,L,W,L,W,W,4.0,11.0,6
4202,Everton,Man United,0.0,1.0,D,0.0,1.0,13.0,17.0,1.0,...,D,L,W,W,D,L,L,11.0,5.0,7
4359,Man United,Everton,1.0,4.0,D,0.0,1.0,18.0,14.0,3.0,...,W,W,L,D,W,W,D,5.0,11.0,7
4493,Man United,Everton,2.0,0.0,H,1.0,0.0,18.0,12.0,8.0,...,L,W,D,W,W,M,M,6.0,7.0,7
4655,Everton,Man United,1.0,0.0,A,0.0,0.0,6.0,15.0,1.0,...,D,D,D,W,W,W,W,7.0,6.0,8
4922,Man United,Everton,2.0,2.0,H,0.0,0.0,7.0,20.0,4.0,...,W,L,W,D,L,W,L,2.0,8.0,7
5168,Everton,Man United,0.0,0.0,H,0.0,0.0,8.0,7.0,1.0,...,W,W,L,W,W,L,L,8.0,2.0,8
5370,Man United,Everton,2.0,3.0,D,2.0,1.0,11.0,13.0,7.0,...,L,D,L,D,L,W,W,6.0,8.0,9

In [36]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HS',
       'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR',
       'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MW', 'HTGS', 'ATGS', 'HTGC',
       'ATGC', 'HTP', 'ATP', 'HM1', 'AM1', 'HM2', 'AM2', 'HM3', 'AM3', 'HM4',
       'AM4', 'HM5', 'AM5', 'HomeTeamLP', 'AwayTeamLP', 'DC', 'HTFormPtsStr',
       'ATFormPtsStr', 'HTFormPts', 'ATFormPts', 'HTWinStreak3',
       'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5', 'ATWinStreak3',
       'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [37]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in last year positions
playing_stat['DiffLP'] = playing_stat['HomeTeamLP'] - playing_stat['AwayTeamLP']

In [38]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP']
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [39]:
#  Clear some columns unuseful 

cols = ['HomeTeam','FTHG', 'FTAG', 'AwayTeam','HomeTeamLP','AwayTeamLP','HTFormPtsStr', 'ATFormPtsStr',
        'HTFormPts', 'ATFormPts','HTGS', 'ATGS', 'HTGC', 'ATGC','HTP','ATP']

''' 'DC', MW', 'FTHG', 'FTAG', 'FTR', 'HTGD', 'ATGD', 'HTP', 'ATP', 'DiffPts', 'DiffLP', 
                , 'HM1', 'HM2', 'HM3','HM4', 'HM5',
                'AM1', 'AM2', 'AM3', 'AM4', 'AM5'
                'DiffFormPts','HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5', 'ATWinStreak3',
                'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5' '''

" 'DC', MW', 'FTHG', 'FTAG', 'FTR', 'HTGD', 'ATGD', 'HTP', 'ATP', 'DiffPts', 'DiffLP', \n                , 'HM1', 'HM2', 'HM3','HM4', 'HM5',\n                'AM1', 'AM2', 'AM3', 'AM4', 'AM5'\n                'DiffFormPts','HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5', 'ATWinStreak3',\n                'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5' "

In [40]:
playing_stat.drop(cols,inplace=True,axis=1)
playing_stat.isnull().sum().sum()

10

In [41]:
playing_stat.iloc[(len(playing_stat)-10):]

,FTR,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
5423,NaN,1.0,0.0,9.0,11.0,3.0,5.0,12.0,8.0,4.0,...,0,0,0,0,0,-0.363636,0.636364,-0.363636,0.136364,7.0
5424,NaN,1.0,0.0,7.0,13.0,4.0,3.0,22.0,11.0,4.0,...,0,0,0,0,0,0.347826,-0.391304,-0.173913,-0.043478,-13.0
5425,NaN,0.0,0.0,9.0,7.0,2.0,1.0,7.0,5.0,3.0,...,0,0,0,0,0,-0.260870,-0.130435,0.130435,-0.086957,-1.0
5426,NaN,4.0,0.0,22.0,6.0,12.0,3.0,12.0,14.0,4.0,...,0,0,0,0,0,1.347826,-1.043478,0.782609,0.260870,-11.0
5427,NaN,0.0,0.0,8.0,10.0,3.0,1.0,7.0,3.0,2.0,...,0,0,0,0,0,-0.434783,-0.913043,-0.260870,0.043478,4.0
5428,NaN,1.0,1.0,16.0,9.0,10.0,4.0,17.0,13.0,4.0,...,0,0,0,0,0,-0.434783,-0.217391,-0.130435,0.260870,9.0
5429,NaN,0.0,1.0,7.0,14.0,2.0,6.0,6.0,7.0,3.0,...,0,0,0,0,0,0.391304,-0.217391,-0.260870,-0.260870,2.0
5430,NaN,1.0,2.0,5.0,18.0,1.0,8.0,12.0,7.0,2.0,...,0,0,0,0,0,-0.478261,0.391304,-0.565217,-0.260870,10.0
5431,NaN,0.0,1.0,7.0,5.0,2.0,5.0,4.0,9.0,3.0,...,0,0,0,0,0,-0.304348,0.869565,-0.913043,-0.130435,6.0
5432,NaN,1.0,1.0,13.0,13.0,7.0,6.0,8.0,18.0,3.0,...,0,0,0,0,0,0.913043,0.304348,1.173913,0.173913,-4.0

In [42]:
def only_hw(string):
    if string == 'H':
        return 'H'
    else:
        return 'NH'
    
#playing_stat['FTR'] = playing_stat.FTR.apply(only_hw)

# Testing set (2019-2020 season)
playing_stat_test = playing_stat.iloc[(len(playing_stat)-len(playing_statistics_1)):len(playing_stat)-10]

In [43]:
playing_stat.to_csv(loc + "final_dataset.csv")
playing_stat_test.to_csv(loc+"test.csv")

In [44]:
len(playing_statistics_1)

229

In [45]:
playing_stat_test

,FTR,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
5204,H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.000000,0.000000,-16.0
5205,A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,-3.000000,0.000000,9.0
5206,D,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,-4.0
5207,H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,3.000000,0.000000,-1.0
5208,D,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5418,H,0.0,1.0,10.0,15.0,4.0,4.0,15.0,12.0,4.0,...,0,0,0,0,0,0.181818,-0.454545,0.909091,0.181818,-12.0
5419,D,0.0,0.0,16.0,5.0,4.0,2.0,6.0,8.0,7.0,...,0,0,0,0,0,-0.181818,-0.409091,0.227273,0.136364,-6.0
5420,A,0.0,1.0,11.0,13.0,5.0,7.0,8.0,8.0,9.0,...,0,1,1,0,0,0.636364,0.954545,-1.454545,-0.363636,2.0
5421,A,0.0,1.0,3.0,9.0,2.0,3.0,12.0,12.0,2.0,...,0,0,0,0,0,-0.954545,-0.363636,-0.090909,-0.272727,3.0
5422,A,2.0,0.0,11.0,16.0,6.0,7.0,10.0,11.0,4.0,...,0,0,0,0,0,-0.181818,1.181818,-1.181818,-0.272727,17.0